# Generated by Django 2.2 on 2020-01-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('ip_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_views', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlasticJam.User')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic_Block',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PlasticJam.User')),
                ('statistic', models.ManyToManyField(to='PlasticJam.Statistic')),
            ],
        ),
    ]
